### ISSUE TITLE
Error handling chromosomes on provided minimal maf file

### ISSUE THREAD

**Issue by ctokheim** [taylor-lab/hotspots#7]
I wanted to look at the full list of mutations in the output for the provided minimal maf file. However, when I did this by relaxing the q-value threshold it resulted in errors in handling mutations with chromosome "MT" or anything starting with "GL" (these are in the MAF file). I have included an error message below:

`Error in .getOneSeqFromBSgenomeMultipleSequences(x, name, start, NA, width,  :
  sequence chrGL000205.1 not found
  Calls: cbind ... lapply -> FUN -> .getOneSeqFromBSgenomeMultipleSequences)`

Collin

**Comment by changmt** [comment]
Error from getOneSeqFromBSgenomeMultipleSequences is likely from the [BSgenome package](https://bioconductor.org/packages/release/bioc/html/BSgenome.html) when attempting to annotate the reference tri-nucleotide context of SNPs. I am not sure how BSgenome handles unmapped scaffolds, if at all. Without the tri-nucleotide context of these SNPs, the method cannot assign significance. FWIW, this shouldn't be affected by relaxing the q-value threshold cutoff since annotating the tri-nucleotide context precedes the actual significance assessment.

Matt

**Comment by ctokheim** [comment]
I have subsequently fixed the hardcoded path in the R script for fasta path by downloading my own fasta using VEP and changing the path within the script. It's a little odd though that the script would completely run through and produce an output file with the default q-value, but then give the above error with a relaxed q-value. That is why I thought there was some interplay with the q-value threshold.

I started running the algorithm on a different pan-cancer dataset and it has been running for 70+ hours. Is that expected/unexpected?

**Comment by ctokheim** [comment]
Ok, it finished running after 130 hours and the output looks fine. I'll close out the issue.
